from typing import Literal

import numpy as np
import numpy.typing as npt
from typing_extensions import TypeAlias

from laddu.data import Dataset, Event

TopologyVertex: TypeAlias = str | list[str]

class VariableExpression:
    def __and__(self, rhs: VariableExpression) -> VariableExpression: ...
    def __or__(self, rhs: VariableExpression) -> VariableExpression: ...
    def __invert__(self) -> VariableExpression: ...

class Topology:
    def __init__(
        self,
        k1: TopologyVertex,
        k2: TopologyVertex,
        k3: TopologyVertex,
        k4: TopologyVertex,
    ) -> None: ...
    @staticmethod
    def missing_k1(k2: TopologyVertex, k3: TopologyVertex, k4: TopologyVertex) -> Topology: ...
    @staticmethod
    def missing_k2(k1: TopologyVertex, k3: TopologyVertex, k4: TopologyVertex) -> Topology: ...
    @staticmethod
    def missing_k3(k1: TopologyVertex, k2: TopologyVertex, k4: TopologyVertex) -> Topology: ...
    @staticmethod
    def missing_k4(k1: TopologyVertex, k2: TopologyVertex, k3: TopologyVertex) -> Topology: ...
    def k1_names(self) -> list[str] | None: ...
    def k2_names(self) -> list[str] | None: ...
    def k3_names(self) -> list[str] | None: ...
    def k4_names(self) -> list[str] | None: ...

class Mass:
    def __init__(self, constituents: list[str]) -> None: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class CosTheta:
    def __init__(
        self,
        topology: Topology,
        daughter: TopologyVertex,
        frame: Literal[
            'Helicity',
            'HX',
            'HEL',
            'GottfriedJackson',
            'Gottfried Jackson',
            'GJ',
            'Gottfried-Jackson',
        ] = 'Helicity',
    ) -> None: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class Phi:
    def __init__(
        self,
        topology: Topology,
        daughter: TopologyVertex,
        frame: Literal[
            'Helicity',
            'HX',
            'HEL',
            'GottfriedJackson',
            'Gottfried Jackson',
            'GJ',
            'Gottfried-Jackson',
        ] = 'Helicity',
    ) -> None: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class Angles:
    costheta: CosTheta
    phi: Phi

    def __init__(
        self,
        topology: Topology,
        daughter: TopologyVertex,
        frame: Literal[
            'Helicity',
            'HX',
            'HEL',
            'GottfriedJackson',
            'Gottfried Jackson',
            'GJ',
            'Gottfried-Jackson',
        ] = 'Helicity',
    ) -> None: ...

class PolAngle:
    def __init__(self, topology: Topology, angle_aux: str) -> None: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class PolMagnitude:
    def __init__(self, magnitude_aux: str) -> None: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class Polarization:
    pol_magnitude: PolMagnitude
    pol_angle: PolAngle

    def __init__(
        self,
        topology: Topology,
        magnitude_aux: str,
        angle_aux: str,
    ) -> None: ...

class Mandelstam:
    def __init__(self, topology: Topology, channel: Literal['s', 't', 'u', 'S', 'T', 'U']) -> None: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...
