[package]
name = "laddu-physics"
version = "0.20.1"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[lints]
workspace = true

[dependencies]
laddu-expr = { version = "0.20.1", path = "../laddu-expr" }
serde.workspace = true
nalgebra.workspace = true
thiserror.workspace = true
num.workspace = true
auto_ops.workspace = true
approx.workspace = true
factorial.workspace = true
indexmap.workspace = true
fastrand.workspace = true
fastrand-contrib.workspace = true


[dev-dependencies]
laddu-compile = { version = "0.20.1", path = "../laddu-compile" }
laddu_runtime.workspace = true
criterion.workspace = true
serde_json.workspace = true
