# .readthedocs.yaml
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    rust: "latest"
  apt_packages:
    - build-essential
    - openmpi-bin
    - openmpi-doc
    - libopenmpi-dev
    - clang
    - mpich
    - libmpich-dev

sphinx:
  configuration: py-laddu/docs/source/conf.py

formats:
  - pdf

python:
  install:
    - method: pip
      path: py-laddu
      extra_requirements:
        - docs
