[package]
name = "laddu-compile"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[lints]
workspace = true

[dependencies]
egg.workspace = true
good_lp.workspace = true
laddu-expr.workspace = true
laddu-cas-macros.workspace = true
laddu-kernel.workspace = true
thiserror.workspace = true
num.workspace = true
serde.workspace = true
