[package]
name = "laddu-compile"
version = "0.19.6"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[lints]
workspace = true

[dependencies]
laddu-expr = { version = "0.19.6", path = "../laddu-expr" }
laddu-kernel = { version = "0.19.6", path = "../laddu-kernel" }
thiserror.workspace = true
num.workspace = true
serde.workspace = true
