[package]
name = "laddu-python"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[lib]
name = "laddu"
crate-type = ["cdylib"]

[dependencies]
laddu-core = { workspace = true, features = [
  "python",
  "jit",
  "wgpu",
] }
pyo3 = { workspace = true, features = ["extension-module"] }
