from contextlib import AbstractContextManager as AbstractContextManager

from . import (
    amplitude,
    amplitudes,
    data,
    experimental,
    extensions,
    io,
    likelihood,
    mpi,
    optimize,
    quantum,
    reaction,
    utils,
    variables,
    vectors,
)
from .amplitude import (
    Evaluator,
    Expression,
    One,
    Parameter,
    Zero,
    expr_product,
    expr_sum,
    parameter,
)
from .amplitudes.angular import (
    BlattWeisskopf,
    ClebschGordan,
    PhotonSDME,
    PolPhase,
    Wigner3j,
    WignerD,
    Ylm,
    Zlm,
)
from .amplitudes.kmatrix import (
    KopfKMatrixA0,
    KopfKMatrixA0Channel,
    KopfKMatrixA2,
    KopfKMatrixA2Channel,
    KopfKMatrixF0,
    KopfKMatrixF0Channel,
    KopfKMatrixF2,
    KopfKMatrixF2Channel,
    KopfKMatrixPi1,
    KopfKMatrixPi1Channel,
    KopfKMatrixRho,
    KopfKMatrixRhoChannel,
)
from .amplitudes.resonance import (
    BreitWigner,
    BreitWignerNonRelativistic,
    Flatte,
    PhaseSpaceFactor,
    Voigt,
)
from .amplitudes.scalar import ComplexScalar, PolarComplexScalar, Scalar, VariableScalar
from .data import BinnedDataset, Dataset, Event
from .likelihood import (
    NLL,
    LikelihoodExpression,
    LikelihoodOne,
    LikelihoodScalar,
    LikelihoodZero,
    StochasticNLL,
    likelihood_product,
    likelihood_sum,
)
from .optimize import (
    ControlFlow,
    EnsembleStatus,
    GradientFreeStatus,
    GradientStatus,
    MCMCObserver,
    MCMCSummary,
    MCMCTerminator,
    MinimizationObserver,
    MinimizationStatus,
    MinimizationSummary,
    MinimizationTerminator,
    integrated_autocorrelation_times,
)
from .quantum import allowed_projections, helicity_combinations
from .reaction import Decay, Particle, Reaction
from .variables import (
    Angles,
    CosTheta,
    Mandelstam,
    Mass,
    Phi,
    PolAngle,
    Polarization,
    PolMagnitude,
)
from .vectors import Vec3, Vec4

__version__: str

def available_parallelism() -> int: ...
def get_threads() -> int: ...
def set_threads(n_threads: int | None) -> None: ...
def threads(n_threads: int | None) -> AbstractContextManager[None, None]: ...

__all__ = [
    'NLL',
    'Angles',
    'BinnedDataset',
    'BlattWeisskopf',
    'BreitWigner',
    'BreitWignerNonRelativistic',
    'ClebschGordan',
    'ComplexScalar',
    'ControlFlow',
    'CosTheta',
    'Dataset',
    'Decay',
    'EnsembleStatus',
    'Evaluator',
    'Event',
    'Expression',
    'Flatte',
    'GradientFreeStatus',
    'GradientStatus',
    'KopfKMatrixA0',
    'KopfKMatrixA0Channel',
    'KopfKMatrixA2',
    'KopfKMatrixA2Channel',
    'KopfKMatrixF0',
    'KopfKMatrixF0Channel',
    'KopfKMatrixF2',
    'KopfKMatrixF2Channel',
    'KopfKMatrixPi1',
    'KopfKMatrixPi1Channel',
    'KopfKMatrixRho',
    'KopfKMatrixRhoChannel',
    'LikelihoodExpression',
    'LikelihoodOne',
    'LikelihoodScalar',
    'LikelihoodZero',
    'MCMCObserver',
    'MCMCSummary',
    'MCMCTerminator',
    'Mandelstam',
    'Mass',
    'MinimizationObserver',
    'MinimizationStatus',
    'MinimizationSummary',
    'MinimizationTerminator',
    'One',
    'Parameter',
    'Particle',
    'PhaseSpaceFactor',
    'Phi',
    'PhotonSDME',
    'PolAngle',
    'PolMagnitude',
    'PolPhase',
    'PolarComplexScalar',
    'Polarization',
    'Reaction',
    'Scalar',
    'StochasticNLL',
    'VariableScalar',
    'Vec3',
    'Vec4',
    'Voigt',
    'Wigner3j',
    'WignerD',
    'Ylm',
    'Zero',
    'Zlm',
    '__version__',
    'allowed_projections',
    'amplitude',
    'amplitudes',
    'data',
    'experimental',
    'expr_product',
    'expr_sum',
    'extensions',
    'get_threads',
    'helicity_combinations',
    'integrated_autocorrelation_times',
    'io',
    'likelihood',
    'likelihood_product',
    'likelihood_sum',
    'mpi',
    'optimize',
    'parameter',
    'quantum',
    'reaction',
    'set_threads',
    'threads',
    'utils',
    'variables',
    'vectors',
]
