from contextlib import AbstractContextManager as AbstractContextManager

from . import amplitudes, data, experimental, extensions, io, mpi, utils
from .amplitudes import (
    Evaluator,
    Expression,
    One,
    Parameter,
    Zero,
    constant,
    expr_product,
    expr_sum,
    parameter,
)
from .amplitudes.breit_wigner import BreitWigner, BreitWignerNonRelativistic
from .amplitudes.common import ComplexScalar, PolarComplexScalar, Scalar, VariableScalar
from .amplitudes.flatte import Flatte
from .amplitudes.kmatrix import (
    KopfKMatrixA0,
    KopfKMatrixA0Channel,
    KopfKMatrixA2,
    KopfKMatrixA2Channel,
    KopfKMatrixF0,
    KopfKMatrixF0Channel,
    KopfKMatrixF2,
    KopfKMatrixF2Channel,
    KopfKMatrixPi1,
    KopfKMatrixPi1Channel,
    KopfKMatrixRho,
    KopfKMatrixRhoChannel,
)
from .amplitudes.phase_space import PhaseSpaceFactor
from .amplitudes.spin_factors import (
    BlattWeisskopf,
    ClebschGordan,
    PhotonSDME,
    Wigner3j,
    WignerD,
)
from .amplitudes.voigt import Voigt
from .amplitudes.ylm import Ylm
from .amplitudes.zlm import PolPhase, Zlm
from .data import BinnedDataset, Dataset, Event
from .extensions import (
    NLL,
    ControlFlow,
    EnsembleStatus,
    GradientFreeStatus,
    GradientStatus,
    LikelihoodEvaluator,
    LikelihoodExpression,
    LikelihoodOne,
    LikelihoodScalar,
    LikelihoodZero,
    MCMCObserver,
    MCMCSummary,
    MCMCTerminator,
    MinimizationObserver,
    MinimizationStatus,
    MinimizationSummary,
    MinimizationTerminator,
    StochasticNLL,
    integrated_autocorrelation_times,
    likelihood_product,
    likelihood_sum,
)
from .utils.angular_momentum import allowed_projections, helicity_combinations
from .utils.variables import (
    Angles,
    CosTheta,
    Decay,
    Mandelstam,
    Mass,
    Particle,
    Phi,
    PolAngle,
    Polarization,
    PolMagnitude,
    Reaction,
)
from .utils.vectors import Vec3, Vec4

__version__: str

def available_parallelism() -> int: ...
def get_threads() -> int: ...
def set_threads(n_threads: int | None) -> None: ...
def threads(n_threads: int | None) -> AbstractContextManager[None, None]: ...

__all__ = [
    'NLL',
    'Angles',
    'BinnedDataset',
    'BlattWeisskopf',
    'BreitWigner',
    'BreitWignerNonRelativistic',
    'ClebschGordan',
    'ComplexScalar',
    'ControlFlow',
    'CosTheta',
    'Dataset',
    'Decay',
    'EnsembleStatus',
    'Evaluator',
    'Event',
    'Expression',
    'Flatte',
    'GradientFreeStatus',
    'GradientStatus',
    'KopfKMatrixA0',
    'KopfKMatrixA0Channel',
    'KopfKMatrixA2',
    'KopfKMatrixA2Channel',
    'KopfKMatrixF0',
    'KopfKMatrixF0Channel',
    'KopfKMatrixF2',
    'KopfKMatrixF2Channel',
    'KopfKMatrixPi1',
    'KopfKMatrixPi1Channel',
    'KopfKMatrixRho',
    'KopfKMatrixRhoChannel',
    'LikelihoodEvaluator',
    'LikelihoodExpression',
    'LikelihoodOne',
    'LikelihoodScalar',
    'LikelihoodZero',
    'MCMCObserver',
    'MCMCSummary',
    'MCMCTerminator',
    'Mandelstam',
    'Mass',
    'MinimizationObserver',
    'MinimizationStatus',
    'MinimizationSummary',
    'MinimizationTerminator',
    'One',
    'Parameter',
    'Particle',
    'PhaseSpaceFactor',
    'Phi',
    'PhotonSDME',
    'PolAngle',
    'PolMagnitude',
    'PolPhase',
    'PolarComplexScalar',
    'Polarization',
    'Reaction',
    'Scalar',
    'StochasticNLL',
    'VariableScalar',
    'Vec3',
    'Vec4',
    'Voigt',
    'Wigner3j',
    'WignerD',
    'Ylm',
    'Zero',
    'Zlm',
    '__version__',
    'allowed_projections',
    'amplitudes',
    'constant',
    'data',
    'experimental',
    'expr_product',
    'expr_sum',
    'extensions',
    'get_threads',
    'helicity_combinations',
    'integrated_autocorrelation_times',
    'io',
    'likelihood_product',
    'likelihood_sum',
    'mpi',
    'parameter',
    'set_threads',
    'threads',
    'utils',
]
