
from pathlib import Path
from typing import Any

def version() -> str: ...
def available_parallelism() -> int: ...

class Amplitude: ...
class AmplitudeID: ...
class AmplitudeOne(Amplitude): ...
class AmplitudeZero(Amplitude): ...
class Evaluator: ...
class Expression: ...
class Manager: ...
class Model: ...
class ParameterLike: ...
class TestAmplitude(Amplitude): ...

def amplitude_product(*args: Any, **kwargs: Any) -> Expression: ...
def amplitude_sum(*args: Any, **kwargs: Any) -> Expression: ...
def constant(value: float) -> ParameterLike: ...
def parameter(name: str) -> ParameterLike: ...

class BreitWigner: ...
class ComplexScalar: ...
class PolarComplexScalar: ...
class Scalar: ...
class PhaseSpaceFactor: ...
class Ylm: ...
class PolPhase: ...
class Zlm: ...

class KopfKMatrixA0: ...
class KopfKMatrixA2: ...
class KopfKMatrixF0: ...
class KopfKMatrixF2: ...
class KopfKMatrixPi1: ...
class KopfKMatrixRho: ...
class PiecewiseScalar: ...
class PiecewiseComplexScalar: ...
class PiecewisePolarComplexScalar: ...

class VariableExpression: ...

class BinnedDataset: ...

class Dataset:
    @staticmethod
    def open(
        path: str | Path,
        *,
        p4s: list[str] | None = ...,
        aux: list[str] | None = ...,
        aliases: dict[str, str | list[str]] | None = ...,
        backend: str | None = ...,
        tree: str | None = ...,
        uproot_kwargs: dict[str, Any] | None = ...,
        amptools_kwargs: dict[str, Any] | None = ...,
    ) -> Dataset: ...

class Event:
    def __init__(
        self,
        p4s: list[Any],
        aux: list[float],
        weight: float,
        *,
        rest_frame_of: list[str] | None = ...,
        p4_names: list[str],
        aux_names: list[str],
    ) -> None: ...

class NLL: ...
class AutocorrelationTerminator: ...
class ControlFlow: ...
class EnsembleStatus: ...
class LikelihoodEvaluator: ...
class LikelihoodExpression: ...
class LikelihoodID: ...
class LikelihoodManager: ...
class LikelihoodOne: ...
class LikelihoodScalar: ...
class LikelihoodTerm: ...
class LikelihoodZero: ...
class MCMCObserver: ...
class MCMCSummary: ...
class MCMCTerminator: ...
class MinimizationObserver: ...
class MinimizationStatus: ...
class MinimizationSummary: ...
class MinimizationTerminator: ...
class StochasticNLL: ...
class Swarm: ...
class SwarmParticle: ...
class Walker: ...

def integrated_autocorrelation_times(*args: Any, **kwargs: Any) -> Any: ...
def likelihood_product(*args: Any, **kwargs: Any) -> LikelihoodExpression: ...
def likelihood_sum(*args: Any, **kwargs: Any) -> LikelihoodExpression: ...

class Angles: ...
class CosTheta: ...
class Mandelstam: ...
class Mass: ...
class Phi: ...
class PolAngle: ...
class PolMagnitude: ...
class Polarization: ...
class Topology: ...
class Vec3: ...
class Vec4: ...

def BinnedGuideTerm(*args: Any, **kwargs: Any) -> LikelihoodTerm: ...
def Regularizer(*args: Any, **kwargs: Any) -> LikelihoodTerm: ...

def finalize_mpi() -> None: ...
def get_rank() -> int: ...
def get_size() -> int: ...
def is_mpi_available() -> bool: ...
def is_root() -> bool: ...
def use_mpi(trigger: bool = ...) -> None: ...
def using_mpi() -> bool: ...
