from types import TracebackType

def use_mpi() -> None: ...
def finalize_mpi() -> None: ...
def using_mpi() -> bool: ...
def is_root() -> bool: ...
def get_rank() -> int: ...
def get_size() -> int: ...

class MPI:
    def __init__(self, *, trigger: bool = True) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool | None: ...

__all__ = [
    'MPI',
    'finalize_mpi',
    'get_rank',
    'get_size',
    'is_root',
    'use_mpi',
    'using_mpi',
]
