from laddu.generation import MassSampler, MomentumSource, VertexGenerator
from laddu.math import Histogram

def energy(value: float) -> MomentumSource: ...
def uniform_energy(min: float, max: float) -> MomentumSource: ...
def histogram_energy(histogram: Histogram) -> MomentumSource: ...
def rest() -> MomentumSource: ...
def uniform_mass(min: float, max: float) -> MassSampler: ...
def histogram_mass(histogram: Histogram) -> MassSampler: ...
def mass_from_properties() -> MassSampler: ...
def t_exponential(slope: float) -> VertexGenerator: ...
def t_histogram(histogram: Histogram) -> VertexGenerator: ...

__all__ = [
    'energy',
    'histogram_energy',
    'histogram_mass',
    'mass_from_properties',
    'rest',
    't_exponential',
    't_histogram',
    'uniform_energy',
    'uniform_mass',
]
