from collections.abc import Sequence
from typing import Literal, TypeAlias

import numpy as np
import numpy.typing as npt

from laddu.amplitude import Expression
from laddu.data import Dataset, Event
from laddu.reaction import Reaction as Reaction

_P4Selection: TypeAlias = str | Sequence[str]

class VariableExpression:
    def __and__(self, rhs: VariableExpression) -> VariableExpression: ...
    def __or__(self, rhs: VariableExpression) -> VariableExpression: ...
    def __invert__(self) -> VariableExpression: ...

class Mass:
    def __init__(self, constituents: _P4Selection) -> None: ...
    def as_expression(self, *tags: str) -> Expression: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...  # ty:ignore[invalid-method-override]
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class CosTheta:
    def as_expression(self, *tags: str) -> Expression: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...  # ty:ignore[invalid-method-override]
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class Phi:
    def as_expression(self, *tags: str) -> Expression: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...  # ty:ignore[invalid-method-override]
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class Angles:
    costheta: CosTheta
    phi: Phi

class PolAngle:
    def __init__(self, reaction: Reaction, pol_angle: str) -> None: ...
    def as_expression(self, *tags: str) -> Expression: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...  # ty:ignore[invalid-method-override]
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class PolMagnitude:
    def __init__(self, pol_magnitude: str) -> None: ...
    def as_expression(self, *tags: str) -> Expression: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...  # ty:ignore[invalid-method-override]
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

class Polarization:
    pol_magnitude: PolMagnitude
    pol_angle: PolAngle

    def __init__(
        self,
        reaction: Reaction,
        *,
        pol_magnitude: str,
        pol_angle: str,
    ) -> None: ...

class Mandelstam:
    def __init__(
        self, reaction: Reaction, channel: Literal['s', 't', 'u', 'S', 'T', 'U']
    ) -> None: ...
    def as_expression(self, *tags: str) -> Expression: ...
    def value(self, event: Event) -> float: ...
    def value_on(self, dataset: Dataset) -> npt.NDArray[np.float64]: ...
    def __eq__(self, value: float) -> VariableExpression: ...  # ty:ignore[invalid-method-override]
    def __lt__(self, value: float) -> VariableExpression: ...
    def __gt__(self, value: float) -> VariableExpression: ...
    def __le__(self, value: float) -> VariableExpression: ...
    def __ge__(self, value: float) -> VariableExpression: ...

__all__ = [
    'Angles',
    'CosTheta',
    'Mandelstam',
    'Mass',
    'Phi',
    'PolAngle',
    'PolMagnitude',
    'Polarization',
    'VariableExpression',
]
