[package]
name = "laddu-autodiff"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
laddu-compile = { path = "../laddu-compile" }
laddu-expr = { path = "../laddu-expr" }
laddu-kernel = { path = "../laddu-kernel" }
num.workspace = true
serde.workspace = true
thiserror.workspace = true
