[package]
name = "laddu-fit"
version = "0.20.1"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[lints]
workspace = true

[dependencies]
ganesh.workspace = true
laddu-expr = { version = "0.20.1", path = "../laddu-expr" }
laddu-likelihood = { version = "0.21.0", path = "../laddu-likelihood" }
laddu-runtime = { version = "0.20.1", path = "../laddu-runtime" }
parking_lot.workspace = true
serde.workspace = true
thiserror.workspace = true

[features]
default = []
python = ["ganesh/python"]
