[package]
name = "laddu-wgpu"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
laddu-runtime = { path = "../laddu-runtime" }
pollster.workspace = true
thiserror.workspace = true
wgpu.workspace = true
