[package]
name = "laddu-wgpu"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bytemuck.workspace = true
laddu-autodiff = { path = "../laddu-autodiff" }
laddu-compile = { path = "../laddu-compile" }
laddu-data = { path = "../laddu-data" }
laddu-expr = { path = "../laddu-expr" }
laddu-kernel = { path = "../laddu-kernel" }
pollster.workspace = true
serde.workspace = true
thiserror.workspace = true
wgpu.workspace = true

[dev-dependencies]
laddu-runtime = { path = "../laddu-runtime" }
serde_json.workspace = true
