[package]
name = "laddu-wgpu"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[lints]
workspace = true

[dependencies]
bytemuck.workspace = true
laddu-autodiff.workspace = true
laddu-compile.workspace = true
laddu-data.workspace = true
laddu-expr.workspace = true
laddu-kernel.workspace = true
pollster.workspace = true
serde.workspace = true
thiserror.workspace = true
wgpu.workspace = true

[dev-dependencies]
laddu-runtime.workspace = true
naga.workspace = true
serde_json.workspace = true
