[package]
name = "laddu"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
laddu-amplitudes = { path = "../laddu-amplitudes", optional = true }
laddu-autodiff = { path = "../laddu-autodiff" }
laddu-compile = { path = "../laddu-compile" }
laddu-data = { path = "../laddu-data" }
laddu-expr = { path = "../laddu-expr" }
laddu-kernel = { path = "../laddu-kernel" }
laddu-likelihood = { path = "../laddu-likelihood", optional = true }
laddu-physics = { path = "../laddu-physics" }
laddu-runtime = { path = "../laddu-runtime" }
laddu-wgpu = { path = "../laddu-wgpu", optional = true }

[features]
default = ["amplitudes", "likelihood"]
amplitudes = ["dep:laddu-amplitudes"]
likelihood = ["dep:laddu-likelihood"]
wgpu = ["dep:laddu-wgpu"]
