[package]
name = "laddu"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
laddu-amplitudes = { path = "../laddu-amplitudes", optional = true }
laddu-autodiff = { path = "../laddu-autodiff" }
laddu-compile = { path = "../laddu-compile" }
laddu-data = { path = "../laddu-data" }
laddu-expr = { path = "../laddu-expr" }
laddu-fit = { path = "../laddu-fit", optional = true }
laddu-generation = { path = "../laddu-generation", optional = true }
laddu-kernel = { path = "../laddu-kernel" }
laddu-likelihood = { path = "../laddu-likelihood", optional = true }
laddu-physics = { path = "../laddu-physics" }
laddu-runtime = { path = "../laddu-runtime" }
laddu-wgpu = { path = "../laddu-wgpu", optional = true }
mpi = { workspace = true, optional = true }
num = { workspace = true, optional = true }
numpy = { workspace = true, optional = true }
pyo3 = { workspace = true, optional = true, features = [
  "experimental-inspect",
  "multiple-pymethods",
  "num-complex",
] }
thiserror.workspace = true

[features]
default = ["amplitudes", "likelihood", "fit", "generation"]
amplitudes = ["dep:laddu-amplitudes"]
likelihood = ["dep:laddu-likelihood"]
fit = ["likelihood", "dep:laddu-fit"]
generation = ["dep:laddu-generation"]
jit = ["laddu-runtime/jit", "laddu-likelihood?/jit", "laddu-generation?/jit"]
mpi = [
  "dep:mpi",
  "laddu-data/mpi",
  "laddu-runtime/mpi",
  "laddu-likelihood?/mpi",
]
wgpu = [
  "dep:laddu-wgpu",
  "laddu-runtime/wgpu",
  "laddu-likelihood?/wgpu",
  "laddu-generation?/wgpu",
]
svg = ["laddu-expr/svg"]
python = [
  "amplitudes",
  "fit",
  "generation",
  "laddu-fit/python",
  "dep:fastrand",
  "dep:num",
  "dep:numpy",
  "dep:pyo3",
]

[dependencies.fastrand]
workspace = true
optional = true

[dev-dependencies]
criterion.workspace = true
num_cpus.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true

[[bench]]
name = "kmatrix_benchmark"
harness = false
required-features = ["jit", "wgpu"]

[[bench]]
name = "jit_benchmark"
harness = false
required-features = ["jit"]

[[example]]
name = "generate_ksks"
required-features = ["generation"]

[[example]]
name = "generate_and_fit_ksks"
required-features = ["generation", "fit"]

[[test]]
name = "generation_fit"
required-features = ["generation", "fit"]
