[package]
name = "laddu"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[lints]
workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
laddu-amplitudes = { workspace = true, optional = true }
laddu-autodiff.workspace = true
laddu-compile.workspace = true
laddu-data.workspace = true
laddu-expr.workspace = true
laddu-fit = { workspace = true, optional = true }
laddu-generation = { workspace = true, optional = true }
laddu-kernel.workspace = true
laddu-likelihood = { workspace = true, optional = true }
laddu-physics.workspace = true
laddu-runtime.workspace = true
laddu-wgpu = { workspace = true, optional = true }
mpi = { workspace = true, optional = true }
num = { workspace = true, optional = true }
numpy = { workspace = true, optional = true }
pyo3 = { workspace = true, optional = true, features = [
  "experimental-inspect",
  "multiple-pymethods",
  "num-complex",
] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror.workspace = true

[features]
default = ["amplitudes", "likelihood", "fit", "generation"]
amplitudes = ["dep:laddu-amplitudes"]
likelihood = ["dep:laddu-likelihood"]
fit = ["likelihood", "dep:laddu-fit"]
generation = ["dep:laddu-generation"]
jit = ["laddu-runtime/jit", "laddu-likelihood?/jit", "laddu-generation?/jit"]
mpi = [
  "dep:mpi",
  "laddu-data/mpi",
  "laddu-runtime/mpi",
  "laddu-likelihood?/mpi",
]
wgpu = [
  "dep:laddu-wgpu",
  "laddu-runtime/wgpu",
  "laddu-likelihood?/wgpu",
  "laddu-generation?/wgpu",
]
svg = ["laddu-expr/svg"]
python = [
  "amplitudes",
  "fit",
  "generation",
  "laddu-fit/python",
  "dep:fastrand",
  "dep:num",
  "dep:numpy",
  "dep:pyo3",
  "dep:serde",
  "dep:serde_json",
]

[dependencies.fastrand]
workspace = true
optional = true

[dev-dependencies]
criterion.workspace = true
fastrand.workspace = true
num_cpus.workspace = true
rayon.workspace = true

[[bench]]
name = "kmatrix_benchmark"
harness = false
required-features = ["jit"]

[[bench]]
name = "jit_benchmark"
harness = false
required-features = ["jit"]

[[bench]]
name = "likelihood_pipeline_benchmark"
harness = false
required-features = ["jit", "likelihood"]

[[example]]
name = "generate_ksks"
required-features = ["generation"]

[[example]]
name = "generate_and_fit_ksks"
required-features = ["generation", "fit"]

[[test]]
name = "generation_fit"
required-features = ["generation", "fit"]
