[package]
name = "laddu-runtime"
version = "0.20.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[lints]
workspace = true

[dependencies]
cranelift = { workspace = true, optional = true }
laddu-autodiff = { version = "0.20.0", path = "../laddu-autodiff" }
laddu-compile = { version = "0.20.0", path = "../laddu-compile" }
laddu-data = { version = "0.20.0", path = "../laddu-data" }
laddu-expr = { version = "0.20.0", path = "../laddu-expr" }
laddu-kernel = { version = "0.20.0", path = "../laddu-kernel" }
laddu-memory = { version = "0.20.0", path = "../laddu-memory" }
laddu-wgpu = { version = "0.20.0", path = "../laddu-wgpu", optional = true }
mpi = { workspace = true, optional = true }
nalgebra.workspace = true
num.workspace = true
rayon.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true

[features]
jit = ["dep:cranelift"]
mpi = ["dep:mpi", "laddu-data/mpi"]
wgpu = ["dep:laddu-wgpu", "laddu-memory/nvml"]
