[package]
name = "laddu-runtime"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
cranelift = { workspace = true, optional = true }
laddu-autodiff = { path = "../laddu-autodiff" }
laddu-compile = { path = "../laddu-compile" }
laddu-data = { path = "../laddu-data" }
laddu-expr = { path = "../laddu-expr" }
laddu-kernel = { path = "../laddu-kernel" }
laddu-wgpu = { path = "../laddu-wgpu", optional = true }
mpi = { workspace = true, optional = true }
nalgebra.workspace = true
num.workspace = true
rayon.workspace = true
thiserror.workspace = true

[features]
jit = ["dep:cranelift"]
mpi = ["dep:mpi", "laddu-data/mpi"]
wgpu = ["dep:laddu-wgpu"]
