[package]
name = "laddu-amplitudes"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
laddu-expr = { path = "../laddu-expr" }
laddu-kernel = { path = "../laddu-kernel" }
laddu-physics = { path = "../laddu-physics" }
num.workspace = true

[dev-dependencies]
laddu-compile = { path = "../laddu-compile" }
laddu-runtime = { path = "../laddu-runtime" }
approx.workspace = true
