[package]
name = "laddu-likelihood"
version = "0.20.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "docs-header.html"]

[lints]
workspace = true

[dependencies]
auto_ops.workspace = true
laddu-compile = { version = "0.20.0", path = "../laddu-compile" }
laddu-data = { version = "0.20.0", path = "../laddu-data" }
laddu-expr = { version = "0.20.0", path = "../laddu-expr" }
laddu-runtime = { version = "0.20.0", path = "../laddu-runtime" }
mpi = { workspace = true, optional = true }
num.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
laddu-amplitudes = { version = "0.20.0", path = "../laddu-amplitudes" }
mpi_test.workspace = true

[features]
jit = ["laddu-runtime/jit"]
mpi = ["dep:mpi", "laddu-data/mpi", "laddu-runtime/mpi"]
wgpu = ["laddu-runtime/wgpu"]
