[package]
name = "laddu-likelihood"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
laddu-compile = { path = "../laddu-compile" }
laddu-data = { path = "../laddu-data" }
laddu-expr = { path = "../laddu-expr" }
laddu-runtime = { path = "../laddu-runtime" }
mpi = { workspace = true, optional = true }
num.workspace = true
thiserror.workspace = true

[dev-dependencies]
approx.workspace = true
laddu-amplitudes = { path = "../laddu-amplitudes" }
mpi_test.workspace = true

[features]
jit = ["laddu-runtime/jit"]
mpi = ["dep:mpi", "laddu-data/mpi", "laddu-runtime/mpi"]
wgpu = ["laddu-runtime/wgpu"]
