[package]
name = "laddu-generation"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
laddu-compile = { path = "../laddu-compile" }
laddu-data = { path = "../laddu-data" }
laddu-expr = { path = "../laddu-expr" }
laddu-physics = { path = "../laddu-physics" }
laddu-runtime = { path = "../laddu-runtime" }
rayon.workspace = true
thiserror.workspace = true

[features]
jit = ["laddu-runtime/jit"]
wgpu = ["laddu-runtime/wgpu"]
